# -*- coding: utf-8 -*-
"""project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUMjiyPEBjkeVnlpzi42cEEgJf5PN6d-
"""

import pandas as pd
import matplotlib.pyplot as plt

print("---------- INJURY REPORT ----------\n\n\n")

#---------- PART 1 ----------
raw_dataframe = pd.read_csv('/content/collegiate_athlete_injury_dataset.csv') #Reading and saving the csv file as dataframe
df_rows, df_cols = raw_dataframe.shape #Storing the number of rows and columns in variables
print
print(f"In total, the dataframe contains {df_cols} columns (traits) and {df_rows} rows (athletes).\n")
raw_dataframe.info() #Displays the info of the dataframe
print("\n")

#---------- PART 2 ----------
clean_df = raw_dataframe.dropna(subset = ['Age', 'Position']) #Delete every row that contains null values either in Age or Position category, and then store the cleaned dataframe

#---------- PART 3 ----------
position_col = clean_df['Position'] #Store the 'Position' column alone
most_freq_value_position = position_col.mode()[0] #Store the most frequent position
print(f"The most frequent value in 'Position' column is: {most_freq_value_position}")

acl_risk_col = clean_df['ACL_Risk_Score'] #Store the 'ACL_Risk_Score' column alone
mean_value_acl_risk = acl_risk_col.mean() #Store the mean value of acl risk
print(f"The mean value in 'ACL_Risk_Score' column is: {round(mean_value_acl_risk, 2)}")

positive_injury_indicator_df = clean_df[clean_df['Injury_Indicator'] == 1] #Store the rows only if 'Injury_Indicator' column value is 1
age_col = positive_injury_indicator_df['Age'] #Store the 'Age' column alone
mean_value_age = age_col.mean() #Store the mean value of age
print(f"The mean value in 'Age' column is: {round(mean_value_age, 2)}\n\n")

#---------- PART 4 ----------
pos_plot = position_col.value_counts().plot(kind = 'bar', title = "Number of athletes in each position") #Store the bar plot of the number of athletes in each position
pos_plot.set_xlabel(xlabel = "Position") #Customizing the x label
pos_plot.set_ylabel(ylabel = "Number of athletes") #Customizing the y label
plt.show()
print("\n\n")

gender_inj_ind_df = gender_injury_table = pd.crosstab(clean_df['Gender'], clean_df['Injury_Indicator']) #Storing a table with two inputs
gender_inj_ind_plot = gender_inj_ind_df.plot(kind = 'bar', stacked = True, title = "Injury Indicator by Gender") #Store the stacked bar plot
gender_inj_ind_plot.set_xlabel("Gender") #Customizing x label
gender_inj_ind_plot.set_ylabel("Number of Athletes") #Customizing y label
plt.legend(title = "Injury Status", labels = ['No Injury', 'Injury']) #Customizing legend
plt.show()

